import { upload } from "https://esm.sh/@vercel/blob/client";
const $=id=>document.getElementById(id); let password=sessionStorage.getItem("portfolio_admin_password")||"", projects=[];
async function api(method="GET",body=null){const opt={method,headers:{"x-admin-password":password}};if(body){opt.headers["content-type"]="application/json";opt.body=JSON.stringify(body)}const r=await fetch("../api/projects",{...opt,cache:"no-store"});if(!r.ok)throw Error("Unauthorized or API error");return r.json()}
async function load(){projects=(await api()).projects||[];render()}
function render(){$("list").innerHTML=projects.map(p=>'<div class="admin-item"><div><b>'+p.title+'</b><small>'+ (p.category||"Project") +' · '+(p.fileUrl?"file attached":"no file")+'</small></div><div><button class="admin-btn ghost" data-edit="'+p.id+'">Edit</button><button class="admin-btn ghost" data-delete="'+p.id+'">Delete</button></div></div>').join("")||"<p>No projects yet.</p>";document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>edit(b.dataset.edit));document.querySelectorAll("[data-delete]").forEach(b=>b.onclick=()=>remove(b.dataset.delete))}
function edit(id){const p=projects.find(x=>x.id===id);if(!p)return;["id","title","category","description","problem","approach","result"].forEach(k=>$(k).value=p[k]||"");$("tools").value=(p.tags||[]).join(", ");scrollTo({top:0,behavior:"smooth"})}
async function remove(id){if(!confirm("Delete this project?"))return;projects=projects.filter(p=>p.id!==id);await api("POST",{projects});render()}
$("loginBtn").onclick=async()=>{password=$("pw").value;try{await load();sessionStorage.setItem("portfolio_admin_password",password);$("login").hidden=true;$("app").hidden=false}catch{$("msg").textContent="Login failed. Check your password."}};
if(password)load().then(()=>{$("login").hidden=true;$("app").hidden=false}).catch(()=>sessionStorage.removeItem("portfolio_admin_password"));
$("logout").onclick=()=>{sessionStorage.removeItem("portfolio_admin_password");location.reload()};
$("clear").onclick=()=>{$("form").reset();$("id").value=""};
$("form").onsubmit=async e=>{e.preventDefault();try{$("status").textContent="Saving…";let id=$("id").value||crypto.randomUUID();let p=projects.find(x=>x.id===id)||{id};p.title=$("title").value.trim();p.category=$("category").value.trim();p.description=$("description").value.trim();p.problem=$("problem").value.trim();p.approach=$("approach").value.trim();p.result=$("result").value.trim();p.tags=$("tools").value.split(",").map(x=>x.trim()).filter(Boolean);p.tools=p.tags.join(" · ");p.number=p.number||String(projects.length+1).padStart(2,"0");let file=$("file").files[0];if(file){$("status").textContent="Uploading "+file.name+"…";const blob=await upload("portfolio/files/"+Date.now()+"-"+file.name,file,{access:"public",handleUploadUrl:"../api/upload",clientPayload:JSON.stringify({password})});p.fileUrl=blob.url;p.fileName=file.name}const i=projects.findIndex(x=>x.id===id);if(i<0)projects.push(p);else projects[i]=p;await api("POST",{projects});$("form").reset();$("id").value="";$("status").textContent="Saved.";render()}catch(err){$("status").textContent=err.message||"Could not save project."}};