import { upload } from "https://esm.sh/@vercel/blob/client";
const $=id=>document.getElementById(id);let password=sessionStorage.getItem("portfolio_admin_password")||"",projects=[];
async function api(method="GET",body=null){const opt={method,headers:{"x-admin-password":password}};if(body){opt.headers["content-type"]="application/json";opt.body=JSON.stringify(body)}const r=await fetch("../api/projects",{...opt,cache:"no-store"});if(!r.ok)throw Error("Unauthorized or API error");return r.json()}
function normalized(){projects.forEach((p,i)=>{if(p.published===undefined)p.published=true;if(p.featured===undefined)p.featured=false;if(p.order===undefined)p.order=i});projects.sort((a,b)=>(a.order??9999)-(b.order??9999))}
async function load(){projects=(await api()).projects||[];normalized();render()}
function render(){normalized();$("list").innerHTML=projects.map((p,i)=>'<div class="admin-item" draggable="true" data-drag="'+p.id+'"><div class="drag-handle">☰</div><div class="admin-item-main">'+(p.imageUrl?'<img class="admin-thumb" src="'+p.imageUrl+'" alt="">':'<div class="admin-thumb placeholder">IMG</div>')+'<div><b>'+escapeHtml(p.title)+'</b><small>'+(p.category||"Project")+' · '+(p.published===false?"Draft":"Published")+(p.featured?" · ★ Featured":"")+' · '+((p.files||[]).length+(p.fileUrl?1:0))+' file(s)</small></div></div><div><button class="admin-btn ghost" data-edit="'+p.id+'">Edit</button><button class="admin-btn ghost" data-delete="'+p.id+'">Delete</button></div></div>').join("")||"<p>No projects yet.</p>";
document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>edit(b.dataset.edit));document.querySelectorAll("[data-delete]").forEach(b=>b.onclick=()=>remove(b.dataset.delete));
let dragged=null;document.querySelectorAll("[data-drag]").forEach(el=>{el.ondragstart=()=>{dragged=el.dataset.drag;el.classList.add("dragging")};el.ondragend=()=>el.classList.remove("dragging");el.ondragover=e=>e.preventDefault();el.ondrop=async e=>{e.preventDefault();if(!dragged||dragged===el.dataset.drag)return;const from=projects.findIndex(x=>x.id===dragged),to=projects.findIndex(x=>x.id===el.dataset.drag);const [moved]=projects.splice(from,1);projects.splice(to,0,moved);projects.forEach((p,i)=>p.order=i);render();$("status").textContent="Saving order…";await api("POST",{projects});$("status").textContent="Order saved."}})}
function escapeHtml(s=""){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function edit(id){const p=projects.find(x=>x.id===id);if(!p)return;["id","title","category","description","problem","approach","result"].forEach(k=>$(k).value=p[k]||"");$("tools").value=(p.tags||[]).join(", ");$("published").checked=p.published!==false;$("featured").checked=!!p.featured;$("thumbnail").value="";$("files").value="";scrollTo({top:0,behavior:"smooth"})}
async function remove(id){if(!confirm("Delete this project?"))return;projects=projects.filter(p=>p.id!==id);projects.forEach((p,i)=>p.order=i);await api("POST",{projects});render()}
$("loginBtn").onclick=async()=>{password=$("pw").value;try{await load();sessionStorage.setItem("portfolio_admin_password",password);$("login").hidden=true;$("app").hidden=false}catch{$("msg").textContent="Login failed. Check your password."}};
if(password)load().then(()=>{$("login").hidden=true;$("app").hidden=false}).catch(()=>sessionStorage.removeItem("portfolio_admin_password"));
$("logout").onclick=()=>{sessionStorage.removeItem("portfolio_admin_password");location.reload()};
$("clear").onclick=()=>{$("form").reset();$("id").value="";$("published").checked=true};
async function uploadFile(file){return upload("portfolio/files/"+Date.now()+"-"+crypto.randomUUID()+"-"+file.name,file,{access:"public",handleUploadUrl:"../api/upload",clientPayload:JSON.stringify({password})})}
$("form").onsubmit=async e=>{e.preventDefault();try{$("status").textContent="Saving…";const id=$("id").value||crypto.randomUUID();let p=projects.find(x=>x.id===id)||{id,order:projects.length};p.title=$("title").value.trim();p.category=$("category").value.trim();p.description=$("description").value.trim();p.problem=$("problem").value.trim();p.approach=$("approach").value.trim();p.result=$("result").value.trim();p.tags=$("tools").value.split(",").map(x=>x.trim()).filter(Boolean);p.tools=p.tags.join(" · ");p.published=$("published").checked;p.featured=$("featured").checked;
const thumb=$("thumbnail").files[0];if(thumb){$("status").textContent="Uploading thumbnail…";const b=await uploadFile(thumb);p.imageUrl=b.url;p.imageName=thumb.name}
const selected=[...$("files").files];if(selected.length){p.files=p.files||[];for(const file of selected){$("status").textContent="Uploading "+file.name+"…";const b=await uploadFile(file);p.files.push({name:file.name,url:b.url})}}
const legacyFiles=p.files||[];if(p.fileUrl&&!legacyFiles.some(f=>f.url===p.fileUrl))legacyFiles.unshift({name:p.fileName||"Project file",url:p.fileUrl});p.files=legacyFiles;const i=projects.findIndex(x=>x.id===id);if(i<0)projects.push(p);else projects[i]=p;projects.forEach((x,i)=>{if(x.order===undefined)x.order=i});await api("POST",{projects});$("form").reset();$("id").value="";$("published").checked=true;$("status").textContent="Saved.";render()}catch(err){$("status").textContent=err.message||"Could not save project."}};